FROM alpine:latest

RUN apk add --no-cache \
    7zip \
    acl \
    busybox \
    file \
    jq \
    libarchive-tools \
    mount \
    util-linux \
    xz

RUN mkdir -p /opt/pinn
RUN mkdir -p /opt/pinn/os
COPY pinn-converter.sh /opt/pinn/

WORKDIR /opt/pinn
ENTRYPOINT ["/opt/pinn/pinn-converter.sh"]
