name: Test

on:
  push:
    branches: [ main ]

jobs:
  prepare:
    name: Datei vorbereiten
    runs-on: ubuntu-latest

    steps:
      - name: Datei herunterladen
        run: |
          mkdir -p shared
          
          wget "https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/armhf/alpine-rpi-3.23.3-armhf.img.gz" -O shared/testimage.img.xz &
          wget "https://downloads.raspberrypi.com/raspios_lite_armhf/Raspberry_Pi_OS_Lite_(32-bit).png" -O shared/testicon.png &

          wait

      - name: Artifact hochladen
        uses: actions/upload-artifact@v4
        with:
          name: shared-data
          path: shared/

  lint-and-test:
    name: ${{ matrix.os }} / ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    needs: prepare

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, debian-latest, alpine-latest]
        arch: [x64, arm64, armhf]

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Artifact herunterladen
        uses: actions/download-artifact@v4
        with:
          name: shared-data
          path: shared

      - name: QEMU einrichten
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3

      - name: Pakete installieren ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y --no-install-recommends 7zip acl fdisk file jq libarchive-tools mount util-linux wget xz-utils shellcheck

      - name: Pakete installieren debian
        if: matrix.os == 'debian-latest'
        run: sudo apt-get install -y --no-install-recommends 7zip acl fdisk file jq libarchive-tools mount util-linux wget xz-utils shellcheck

      - name: Pakete installieren alpine
        if: matrix.os == 'alpine-latest'
        run: sudo apk add 7zip acl busybox file jq libarchive-tools mount util-linux wget xz shellcheck

      - name: ShellCheck ausführen
        run: shellcheck ./pinn-converter.sh

      - name: Bash-Skript ausführbar machen
        run: chmod +x ./pinn-converter.sh

      - name: Bash-Skript ausführen
        run: sudo ./pinn-converter.sh -f ./shared/testimage.img.xz -c ./shared/testicon.png -n "raspios_armhf_lite" -d "A port of Debian with no desktop environment" -u "http://www.raspbian.org/" -t $(date +%F) -m trixie -p "Pi Model, Pi 2, Pi 3, Pi 4, Pi 5, Pi Zero, Pi Zero 2, Pi Compute Module 3, Pi Compute Module 4, Pi Compute Module 5" 

      - name: Prüfe ob Datein existieren
        id: check_files
        uses: thebinaryfelix/check-file-existence-action@2.0.0
        with:
          files: 'os/raspios_armhf_lite/boot.tar.xz, os/raspios_armhf_lite/os.json, os/raspios_armhf_lite/partition_setup.sh, os/raspios_armhf_lite/partitions.json, os/raspios_armhf_lite/raspios_armhf_lite.png, os/raspios_armhf_lite/root.tar.xz'

      - name: Fehler
        if: steps.check_files.outputs.exists == 'false'
        run: exit 1
