name: Docker

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata debian
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            docker.io/smhrambo/pinn-converter
            ghcr.io/smhrambo/pinn-converter
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=
          flavor: |
            latest=true
            suffix=debian

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push debian
        id: build-and-push-debian
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            docker.io/smhrambo/pinn-converter:latest
            docker.io/smhrambo/pinn-converter:1.0.0
            docker.io/smhrambo/pinn-converter:debian
            docker.io/smhrambo/pinn-converter:latest-debian
            docker.io/smhrambo/pinn-converter:1.0.0-debian
            ghcr.io/smhrambo/pinn-converter:latest
            ghcr.io/smhrambo/pinn-converter:1.0.0
            ghcr.io/smhrambo/pinn-converter:debian
            ghcr.io/smhrambo/pinn-converter:latest-debian
            ghcr.io/smhrambo/pinn-converter:1.0.0-debian

      - name: Build and push alpine
        id: build-and-push-alpine
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.alpine
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            docker.io/smhrambo/pinn-converter:alpine
            docker.io/smhrambo/pinn-converter:latest-alpine
            docker.io/smhrambo/pinn-converter:1.0.0-alpine
            ghcr.io/smhrambo/pinn-converter:alpine
            ghcr.io/smhrambo/pinn-converter:latest-alpine
            ghcr.io/smhrambo/pinn-converter:1.0.0-alpine

      - name: Sign the published Docker image debian
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: "docker.io/smhrambo/pinn-converter:latest", "docker.io/smhrambo/pinn-converter:1.0.0", "docker.io/smhrambo/pinn-converter:debian", "docker.io/smhrambo/pinn-converter:latest-debian", "docker.io/smhrambo/pinn-converter:1.0.0-debian"
          DIGEST: ${{ steps.build-and-push-debian.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Sign the published Docker image aloine
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: alpine, latest-alpine, 1.0.0-alpine
          DIGEST: ${{ steps.build-and-push-alpine.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
